### ISSUE TITLE
This is a great idea! Does it work with Nuxt 3?

### ISSUE THREAD

**Issue by notflip** [KlemenS189/Translator#14]

**Comment by KlemenS189** [comment]
Hey. It's been a while since I have done anything on this repo :)
I have just tried on a nuxt 3 repo and it doesn't work as expected. I would need to look into it.

**Comment by KlemenS189** [comment]
@notflip I updated the repo. It works also in nuxt 3.
The package looks for $t('tag.tag...') in all `.vue, .js, .ts` files in pages, components and layouts folder.

**Comment by notflip** [comment]
That's great! I'm going to test it out, thanks a lot!

**Comment by KlemenS189** [comment]
I am going to close this issue. Feel free to reopen it if any issues occur.
