### ISSUE TITLE
when i run translator or translator anything will error command not found: translator

### ISSUE THREAD

**Issue by HappyColour** [KlemenS189/Translator#4]

**Comment by KlemenS189** [comment]
Hey, can you paste the error stack trace here?

**Comment by HappyColour** [comment]
Sure.
success Saved 1 new dependency.
info Direct dependencies
└─ @razmooo/translator@0.2.2
info All dependencies
└─ @razmooo/translator@0.2.2
✨  Done in 4.83s.
20:52 zeus@Zeusxs-MacBook-Pro /Users/zeus/Heaven/Niu_i18n
% translator lang/en.js 
zsh: command not found: translator

**Comment by HappyColour** [comment]
> Hey, can you paste the error stack trace here?

Could you provide a nuxt-i18n example please ?

**Comment by KlemenS189** [comment]
@HappyColour Hey. Sorry for a so late response. You can check the updated version.

**Comment by HappyColour** [comment]
> @HappyColour Hey. Sorry for a so late response. You can check the updated version.

Thx your reply, i have already fixed it.
